version: '3.8'

services:
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - '3000:3000'
      environment:
        NODE_ENV: .env
      volumes:
        - ./backend:/app
      depends_on:
        - postgres
      networks:
        - nexus
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - nexus

  pgadmin4:
    image: dpage/pgadmin4
    user: "${UID}:${GID}" # to avoid permission issues
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    ports:
      - "5444:80"
    depends_on:
      - postgres
    networks:
      - nexus


networks:
  nexus:
    driver: bridge